version: '3.8'

services:
  worker1:
    build: .
    container_name: crypten_worker1
    command: python -m worker call tasks.mpc:linreg_homework_compare
    environment:
      - RENDEZVOUS=env://
      - MASTER_ADDR=worker1
      - MASTER_PORT=29500
      - WORLD_SIZE=2          
      - RANK=0              
      - CRYPTEN_PROVIDER_NAME=TTP
      - PRECISION=16          
      - EPOCHS=30             
      - BATCH_SIZE=512       
      - LOGLEVEL=INFO
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data/worker1:/data/linreg
      - ./data/homework:/data/linreg/homework
    networks:
      - crypten_network
    depends_on:
      - ttp

  worker2:
    build: .
    container_name: crypten_worker2
    command: python -m worker call tasks.mpc:linreg_homework_compare
    environment:
      - RENDEZVOUS=env://
      - MASTER_ADDR=worker1  
      - MASTER_PORT=29500
      - WORLD_SIZE=2         
      - RANK=1              
      - CRYPTEN_PROVIDER_NAME=TTP
      - PRECISION=16
      - EPOCHS=30
      - BATCH_SIZE=512
      - LOGLEVEL=INFO
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data/worker2:/data/linreg
      - ./data/homework:/data/linreg/homework
    networks:
      - crypten_network
    depends_on:
      - worker1
      - ttp

  ttp:
    build: .
    container_name: crypten_ttp
    command: python -m worker call tasks.mpc:ttp
    environment:
      - RENDEZVOUS=env://
      - MASTER_ADDR=worker1
      - MASTER_PORT=29500
      - WORLD_SIZE=2          
      - RANK=2               
      - CRYPTEN_PROVIDER_NAME=TTP
      - PRECISION=16
      - LOGLEVEL=ERROR
      - PYTHONUNBUFFERED=1
    networks:
      - crypten_network
    restart: unless-stopped
networks:
  crypten_network:
    driver: bridge
